name: build pocketmine
on:
  push:
    branches:
      - main
    paths:
      - pocketmine/**

jobs:
  push:
    name: "eggs:pocketmine_v${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 4
          - 5
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - uses: docker/build-push-action@v5
        with:
          context: ./pocketmine
          file: ./pocketmine/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: PMMP_Version=${{ matrix.tag }}
          tags: |
            ghcr.io/carsonlenze/eggs:pocketmine_v${{ matrix.tag }}